const coursedata = [
    {
        id: 1,
        thumbnail: 'assets/images/courses/courses-1.jpg',
        price: 39,
        price1: 99,
        badge_all: 'All Levels',
        category: 'Communications',
        title: 'Successful Negotiation: Master Your Negotiating Skills',
        description: 'Negotiation is a skill well worth mastering - by putting …',
        rating_average: '5.0',
        rating_total: '/5',
    },
    {
        id: 2,
        thumbnail: 'assets/images/courses/courses-2.jpg',
        price: 39,
        price1: 99,
        badge_all: 'All Levels',
        category: 'Communications',
        title: 'Successful Negotiation: Master Your Negotiating Skills',
        description: 'Negotiation is a skill well worth mastering - by putting …',
        rating_average: '5.0',
        rating_total: '/5',
    },
    {
        id: 3,
        thumbnail: 'assets/images/courses/courses-3.jpg',
        price: 39,
        price1: 99,
        badge_all: 'All Levels',
        category: 'Communications',
        title: 'Successful Negotiation: Master Your Negotiating Skills',
        description: 'Negotiation is a skill well worth mastering - by putting …',
        rating_average: '5.0',
        rating_total: '/5',
    },
    {
        id: 4,
        thumbnail: 'assets/images/courses/courses-4.jpg',
        price: 39,
        price1: 99,
        badge_all: 'All Levels',
        category: 'Communications',
        title: 'Successful Negotiation: Master Your Negotiating Skills',
        description: 'Negotiation is a skill well worth mastering - by putting …',
        rating_average: '5.0',
        rating_total: '/5',
    },
    {
        id: 5,
        thumbnail: 'assets/images/courses/courses-5.jpg',
        price: 39,
        price1: 99,
        badge_all: 'All Levels',
        category: 'Communications',
        title: 'Successful Negotiation: Master Your Negotiating Skills',
        description: 'Negotiation is a skill well worth mastering - by putting …',
        rating_average: '5.0',
        rating_total: '/5',
    },
    {
        id: 6,
        thumbnail: 'assets/images/courses/courses-6.jpg',
        price: 39,
        price1: 99,
        badge_all: 'All Levels',
        category: 'Communications',
        title: 'Successful Negotiation: Master Your Negotiating Skills',
        description: 'Negotiation is a skill well worth mastering - by putting …',
        rating_average: '5.0',
        rating_total: '/5',
    },
    {
        id: 7,
        thumbnail: 'assets/images/courses/courses-7.jpg',
        price: 39,
        price1: 99,
        badge_all: 'All Levels',
        category: 'Communications',
        title: 'Successful Negotiation: Master Your Negotiating Skills',
        description: 'Negotiation is a skill well worth mastering - by putting …',
        rating_average: '5.0',
        rating_total: '/5',
    },
    {
        id: 8,
        thumbnail: 'assets/images/courses/courses-8.jpg',
        price: 39,
        price1: 99,
        badge_all: 'All Levels',
        category: 'Communications',
        title: 'Successful Negotiation: Master Your Negotiating Skills',
        description: 'Negotiation is a skill well worth mastering - by putting …',
        rating_average: '5.0',
        rating_total: '/5',
    },
]

export default coursedata;